Update

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -83,7 +83,7 @@ jobs:
 
   srs:
     name: "FFmpeg with SRS"
-    #needs: build
+    needs: build
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
@@ -97,16 +97,9 @@ jobs:
 
           # Build FFmpeg with WebRTC support
           ./configure --enable-muxer=whip --enable-openssl --enable-version3 \
-            --enable-libx264 --enable-gpl --enable-libopus \
-            --extra-cflags='-fsanitize=address -g -O0' --extra-cxxflags='-fsanitize=address -g -O0' --extra-ldflags='-fsanitize=address -g -O0'
+            --enable-libx264 --enable-gpl --enable-libopus
           make -j$(nproc)
           ./ffmpeg -version && ./ffmpeg -muxers 2>/dev/null |grep whip
-      - name: Setup Coredump
-        run: |
-          set -euxo pipefail
-          sudo apt-get install -y gdb
-          ulimit -c unlimited
-          echo '/tmp/core.%e.%p' | sudo tee /proc/sys/kernel/core_pattern
       - name: Start SRS Docker container
         run: |
           set -euxo pipefail
@@ -122,7 +115,62 @@ jobs:
           nohup ./ffmpeg -t 30 -re -f lavfi -i testsrc=size=1280x720 -f lavfi -i sine=frequency=440 -pix_fmt yuv420p \
             -vcodec libx264 -profile:v baseline -r 25 -g 50 -acodec libopus -ar 48000 -ac 2 \
             -f whip "http://localhost:1985/rtc/v1/whip/?app=live&stream=livestream" \
-            >ffstdout.log 2>ffstderr.log &
+            >/dev/null 2>&1 &
+          
+          # Check streams in SRS.
+          for ((i=0; i<10; i++)); do
+            STREAM=$(curl -s http://localhost:1985/api/v1/streams/ | jq -r '.streams[].name')
+            if [[ "$STREAM" == "livestream" ]]; then echo 'Test OK'; break; fi
+            sleep 3
+          done
+          if [[ "$STREAM" != "livestream" ]]; then
+            echo "Stream not found: $STREAM"
+            exit 1
+          fi
+    runs-on: ubuntu-22.04
+
+  asan:
+    name: "FFmpeg with Asan"
+    #needs: build
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+      - name: Setup Coredump
+        run: |
+          set -euxo pipefail
+          sudo apt-get install -y gdb
+          ulimit -c unlimited
+          echo '/tmp/core.%e.%p' | sudo tee /proc/sys/kernel/core_pattern
+      - name: Build FFmpeg
+        run: |
+          set -euxo pipefail
+
+          # Install dependencies
+          sudo apt-get update
+          sudo apt-get install -y nasm pkg-config jq libssl-dev libopus-dev libx264-dev
+
+          # Build FFmpeg with WebRTC support
+          ./configure --enable-muxer=whip --enable-openssl --enable-version3 \
+            --enable-libx264 --enable-gpl --enable-libopus \
+            --extra-cflags='-fsanitize=address -g -O0' --extra-cxxflags='-fsanitize=address -g -O0' --extra-ldflags='-fsanitize=address -g -O0'
+          make -j$(nproc)
+          ./ffmpeg -version && ./ffmpeg -muxers 2>/dev/null |grep whip
+      - name: Start SRS Docker container
+        run: |
+          set -euxo pipefail
+          ip=$(ifconfig eth0 | grep 'inet ' | awk '{print $2}')
+          docker run --rm -d -p 1935:1935 -p 1985:1985 -p 8080:8080 \
+              --env CANDIDATE=$ip -p 8000:8000/udp \
+              ossrs/srs:5 ./objs/srs -c conf/rtc2rtmp.conf
+      - name: Test FFmpeg with SRS
+        run: |
+          set -euxo pipefail
+
+          # Publish a test stream to SRS using the whip muxer
+          nohup ./ffmpeg -t 30 -re -f lavfi -i testsrc=size=1280x720 -f lavfi -i sine=frequency=440 -pix_fmt yuv420p \
+            -vcodec libx264 -profile:v baseline -r 25 -g 50 -acodec libopus -ar 48000 -ac 2 \
+            -f whip "http://localhost:1985/rtc/v1/whip/?app=live&stream=livestream" \
+            1>ffstdout.log 2>ffstderr.log &
           
           # Check streams in SRS.
           for ((i=0; i<10; i++)); do
@@ -137,17 +185,33 @@ jobs:
 
           # TEST: Generate a coredump.
           pkill -SIGSEGV ffmpeg
+          sleep 3
       - name: Show FFmpeg Stdout Log
         run: cat ffstdout.log
       - name: Show FFmpeg Stderr Log
         run: cat ffstderr.log
       - name: Find core dumps
         run: |
+          set -euxo pipefail
+          shopt -s nullglob
+          files=(/tmp/core.*)
+          if [[ ${#files[@]} -eq 0 ]]; then
+            echo "No core dumps found."
+            exit 0
+          fi
           for core in /tmp/core.*; do
             echo "Core dump found: $core"
             gdb -q -c "$core" -ex "bt" -ex "quit"
             exit 1
           done
+      - name: Check Asan Log
+        run: |
+          set -euxo pipefail
+
+          cat ffstderr.log |grep 'ERROR: AddressSanitizer' && 
+          echo "AddressSanitizer error found in ffstderr.log" && exit 1
+
+          echo "AddressSanitizer is ok"
     runs-on: ubuntu-22.04
 
   openssl-1-0-1k:
@@ -440,6 +504,7 @@ jobs:
     needs:
       - fate
       - srs
+      - asan
       - openssl-1-0-1k
       - openssl-1-0-2
       - openssl-1-1-0h
