Update

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -143,6 +143,68 @@ jobs:
 
   asan:
     name: "FFmpeg with Asan"
+    needs: build
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+      - name: Build FFmpeg
+        run: |
+          set -euxo pipefail
+
+          # Install dependencies
+          sudo apt-get update
+          sudo apt-get install -y nasm pkg-config jq libssl-dev libopus-dev libx264-dev
+
+          # Build FFmpeg with WebRTC support
+          ./configure --enable-muxer=whip --enable-openssl --enable-version3 \
+            --enable-libx264 --enable-gpl --enable-libopus \
+            --extra-cflags='-fsanitize=address -g -O0' --extra-cxxflags='-fsanitize=address -g -O0' --extra-ldflags='-fsanitize=address -g -O0'
+          make -j$(nproc)
+          ./ffmpeg -version && ./ffmpeg -muxers 2>/dev/null |grep whip
+      - name: Start SRS Docker container
+        run: |
+          set -euxo pipefail
+          ip=$(ifconfig eth0 | grep 'inet ' | awk '{print $2}')
+          docker run --rm -d -p 1935:1935 -p 1985:1985 -p 8080:8080 \
+              --env CANDIDATE=$ip -p 8000:8000/udp \
+              ossrs/srs:5 ./objs/srs -c conf/rtc2rtmp.conf
+      - name: Test FFmpeg with SRS
+        run: |
+          set -euxo pipefail
+
+          # Publish a test stream to SRS using the whip muxer
+          nohup ./ffmpeg -t 30 -re -f lavfi -i testsrc=size=1280x720 -f lavfi -i sine=frequency=440 -pix_fmt yuv420p \
+            -vcodec libx264 -profile:v baseline -r 25 -g 50 -acodec libopus -ar 48000 -ac 2 \
+            -f whip "http://localhost:1985/rtc/v1/whip/?app=live&stream=livestream" \
+            1>ffstdout.log 2>ffstderr.log &
+          
+          # Check streams in SRS.
+          for ((i=0; i<10; i++)); do
+            STREAM=$(curl -s http://localhost:1985/api/v1/streams/ | jq -r '.streams[].name')
+            if [[ "$STREAM" == "livestream" ]]; then echo 'Test OK'; break; fi
+            sleep 3
+          done
+          if [[ "$STREAM" != "livestream" ]]; then
+            echo "Stream not found: $STREAM"
+            exit 1
+          fi
+
+          # Stop FFmpeg normally.
+          pkill ffmpeg
+      - name: Show FFmpeg Stdout Log
+        run: cat ffstdout.log
+      - name: Show FFmpeg Stderr Log
+        run: cat ffstderr.log
+      - name: Check Asan Log
+        run: |
+          set -euxo pipefail
+          cat ffstderr.log |grep 'ERROR: AddressSanitizer' && 
+            echo "AddressSanitizer error found in ffstderr.log" && exit 1
+          echo "AddressSanitizer is ok"
+    runs-on: ubuntu-22.04
+
+  coredump:
+    name: "FFmpeg with Coredump"
     #needs: build
     steps:
       - name: Checkout repository
@@ -154,6 +216,7 @@ jobs:
           sudo apt-get update
           sudo apt-get install -y gdb
 
+          # See https://github.com/itamarst/gha-upload-cores/blob/main/.github/workflows/build.yml
           sudo mkdir /cores
           sudo chmod 777 /cores
           sudo bash -c 'echo "/cores/core.%e.%p.%t" > /proc/sys/kernel/core_pattern'
@@ -611,6 +674,7 @@ jobs:
       - fate
       - srs
       - asan
+      - coredump
       - openssl-1-0-1k
       - openssl-1-0-2
       - openssl-1-1-0h
